"""add auth_settings table

Revision ID: 2ec4eb10311d
Revises: 9a09f50283d8
Create Date: 2026-08-26 17:49:54.068176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec4eb10311d'
down_revision = '9a09f50283d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_password', sa.String(length=120), nullable=False),
    sa.Column('worker_password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_settings')
    # ### end Alembic commands ###
