"""Adding a new Tabel for Bils,

Revision ID: f5eb9e1728e2
Revises: 541126320b95
Create Date: 2026-08-11 20:51:00.047502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5eb9e1728e2'
down_revision = '541126320b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bils',
    sa.Column('bil_id', sa.Integer(), nullable=False),
    sa.Column('bil_category', sa.String(length=50), nullable=False),
    sa.Column('campany', sa.String(length=50), nullable=False),
    sa.Column('bil_price', sa.Float(), nullable=False),
    sa.Column('bil_paid_amount', sa.Float(), nullable=True),
    sa.Column('bil_remain_amount', sa.Float(), nullable=False),
    sa.Column('bil_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('bil_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bils')
    # ### end Alembic commands ###
